services:
  - type: web
    name: bagels
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: TTYD_CREDENTIALS
        value: admin:admin
    disk:
      name: bagels-data
      size_gb: 1
